# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChalkUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChalkUp
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'SwiftyJSON'
  pod 'Nuke'
  pod 'SDWebImage', '~> 5.0'
end
